# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk12

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - kapchevich@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
    env:
      global:
      - CODECOV_TOKEN="ecdd7a6f-aa50-409d-8e8b-6a87c1d2b8c6"